version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass redispassword --appendonly yes 

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: url_shortner
    ports:
      - "3306:3306"
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
