server:
  port: 8085
  id: 1
  domain: http://localhost:8085/

spring:
  application:
    name: url-shortner
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/block-storage?serverTimezone=UTC&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: root
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
      connection-timeout: 30000     # 30?
      max-lifetime: 1800000         # 30?
      idle-timeout: 600000          # 10?
      keepalive-time: 60000         # 1?
      validation-timeout: 5000      # 5?
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        jdbc:
          batch_size: 50
        order_updates: true
        order_inserts: true
    defer-datasource-initialization: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}
    stack:
      auto: false