version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: block-storage-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: block_storage 
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5