server:
  port: 8086
  id: 2

spring:
  application:
    name: fanout-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
  data:
    redis:
      host: localhost
      port: 6380
      password: redispassword
